test1 = imread('.\origin\1.jpg');
test2 = imread('.\origin\2.bmp');
test3 = imread('.\origin\3.bmp');
test4 = imread('.\origin\4.bmp');
test5 = imread('.\origin\5.bmp'); 
test6 = imread('.\origin\6.jpg');
test7 = imread('.\origin\7.tif');
test8 = imread('.\origin\8.x-png');
% medianFilter(test3);
% histEqual(test5);
% tempData6 = intrans(test6);
% motionBlur(test7);
% test1=rgb2gray(test1);
MN=[5 110];
SE = strel('line', 10, 90);
SE2 = strel('rectangle',MN);
test = imerode(test1, SE);
test = imdilate(test, SE2);
test = rgb2gray(test);
test(test<210) = 0;
imshow(test);